# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from

# Site settings
title: "박맹의 블로그"
description: "쓰고싶은거 쓰는 블로그"
email: 'qkraudghgh@gmail.com'
#blog logo
logo: ""
# blog cover
cover: ""

authors:
   Myoungho Pak:
     name: Myoungho Pak
     image: https://qkraudghgh.github.io/assets/images/profile.JPG

paginate: 5

url: "http://" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@'

#fill in disqus shortname to use disqus
disqus: ''

timezone: Asia/Seoul

# social icons and sharing options
social:

  - icon: facebook
    url: http://fb.me/myounghoPak
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/qkraudghgh
    desc: Our GitHub
    share_url:
    share_title:
    share_link:
